#!/bin/bash
# Generate daily briefing for General

echo "========================================"
echo "  🎖️ DAILY BRIEFING — $(date '+%A, %B %d, %Y')"
echo "========================================"
echo ""

# System Status
echo "📊 SYSTEM STATUS:"
echo "   Disk: $(df -h / | tail -1 | awk '{print $5}') ($(df -h / | tail -1 | awk '{print $4}') free)"
echo "   Memory: $(free -h | grep Mem | awk '{print $3"/"$2}')"
echo "   Load: $(cat /proc/loadavg | awk '{print $1}')"
echo ""

# Agent Summary
echo "🤖 AGENT SUMMARY:"
echo "   Active Agents: 30 (15 main + 15 sub)"
echo "   Active Tasks: 60+ concurrent missions"
echo ""

# Yesterday's Completions (check logs)
echo "✅ RECENT COMPLETIONS:"
ls -lt ~/.openclaw/workspace/*/ 2>/dev/null | head -5 | while read line; do
    echo "   $line"
done
echo ""

# Today's Focus
echo "🎯 TODAY'S FOCUS:"
echo "   • Check #needed channel for decisions"
echo "   • Review agent progress in Discord"
echo "   • Monitor dashboard for updates"
echo ""

# Pending Decisions
echo "⏰ PENDING DECISIONS:"
echo "   • X API credentials (Hype Man ready)"
echo "   • Custom domain purchase"
echo "   • Local node hardware (Pi 5 vs NUC)"
echo ""

echo "========================================"
echo "  Generated by The Butler | Life OS"
echo "========================================"
