#!/bin/bash
# PDF Report Generator & Discord Uploader
# Creates PDF reports and uploads them to Discord channels

LOG_FILE="~/.openclaw/logs/pdf-reports.log"
DATE=$(date '+%Y-%m-%d')
TIME=$(date '%I:%M %p %Z')

echo "========================================" >> $LOG_FILE
echo "📄 PDF REPORT GENERATOR - $DATE" >> $LOG_FILE
echo "========================================" >> $LOG_FILE

# Function to generate PDF from markdown
 generate_pdf() {
    local input_file="$1"
    local output_file="$2"
    local title="$3"
    
    # Check if pandoc is available
    if command -v pandoc &> /dev/null; then
        pandoc "$input_file" -o "$output_file" --pdf-engine=xelatex \
            -V geometry:margin=1in \
            -V colorlinks=true \
            -V linkcolor=blue \
            -V urlcolor=blue
        echo "✅ PDF generated: $output_file" >> $LOG_FILE
    else
        # Fallback: just copy as markdown
        cp "$input_file" "${output_file%.pdf}.md"
        echo "⚠️ Pandoc not available, using markdown" >> $LOG_FILE
    fi
}

# Generate morning brief PDF
generate_morning_brief_pdf() {
    echo "🌅 Generating morning brief PDF..." >> $LOG_FILE
    
    cat > /tmp/morning-brief-report.md << 'EOF'
---
title: Life OS Morning Brief
date: $(date '+%Y-%m-%d')
---

# 🌅 Morning Brief - $(date '+%A, %B %d, %Y')

## 📋 Executive Summary
- **System Status:** Nominal ✅
- **Active Agents:** 30
- **Tasks In Progress:** 60+
- **System Uptime:** $(uptime -p 2>/dev/null || echo "Check dashboard")

## 🌤️ Weather
Local weather data placeholder

## ✅ Today's Priorities
1. Review overnight proactive builds
2. Check Discord notifications
3. Review PRs from Claw
4. Morning sync with team

## 🤖 Agent Status
All 15 agents operational

## 💡 Recommendation
Focus on one important task today.
Progress over perfection.

---
*Generated by Life OS | $(date '+%I:%M %p %Z')*
EOF
    
    # Generate PDF or use markdown
    if command -v pandoc &> /dev/null; then
        pandoc /tmp/morning-brief-report.md -o /tmp/morning-brief-${DATE}.pdf 2>/dev/null || \
        cp /tmp/morning-brief-report.md /tmp/morning-brief-${DATE}.md
    else
        cp /tmp/morning-brief-report.md /tmp/morning-brief-${DATE}.md
    fi
    
    echo "✅ Morning brief report created" >> $LOG_FILE
}

# Upload to Discord
upload_to_discord() {
    local file_path="$1"
    local channel_name="$2"
    local title="$3"
    
    export DISCORD_BOT_TOKEN=$(cat ~/.openclaw/discord/bot.token 2>/dev/null)
    
    if [ -z "$DISCORD_BOT_TOKEN" ]; then
        echo "⚠️ No Discord token" >> $LOG_FILE
        return
    fi
    
    python3 << PYDISCORD
import discord
import os

token = os.environ.get('DISCORD_BOT_TOKEN')
file_path = """$file_path"""
channel_name = """$channel_name"""
title = """$title"""

class FileUploader(discord.Client):
    async def on_ready(self):
        for guild in self.guilds:
            if "Life" in guild.name:
                channel = discord.utils.get(guild.text_channels, name=channel_name)
                if channel and os.path.exists(file_path):
                    filename = os.path.basename(file_path)
                    
                    embed = discord.Embed(
                        title=title,
                        description=f"📄 {filename}",
                        color=0x00d4ff
                    )
                    embed.set_footer(text="Hosted on Discord CDN | Download available anytime")
                    
                    with open(file_path, 'rb') as f:
                        file = discord.File(f, filename=filename)
                        await channel.send(embed=embed, file=file)
                    
                    print(f"✅ Uploaded {filename} to #{channel_name}")
                break
        await self.close()

intents = discord.Intents.default()
client = FileUploader(intents=intents)
client.run(token)
PYDISCORD
}

# Main execution based on argument
case "$1" in
    morning)
        generate_morning_brief_pdf
        upload_to_discord "/tmp/morning-brief-${DATE}.md" "morning-brief" "🌅 Morning Brief PDF"
        ;;
    afternoon)
        # Similar for afternoon research
        upload_to_discord "/tmp/afternoon-research-${DATE}.md" "afternoon-brief" "🕓 Research Report"
        ;;
    status)
        # Generate and upload status report
        echo "📊 Status report upload" >> $LOG_FILE
        ;;
    *)
        echo "Usage: $0 {morning|afternoon|status}" >> $LOG_FILE
        ;;
esac

echo "✅ PDF report process complete" >> $LOG_FILE
echo "" >> $LOG_FILE
